### ISSUE TITLE
Displaying multiple clusters on the same dashboard

### ISSUE THREAD

**Issue by gurrie** [yammer/breakerbox#15]
Hi,

I am not sure whether this is actually possible, but I would be interested to hear how other people handle this. I have an environment with a number of different services running in it. Each of the services communicate with each other using Hystrix and I would like to understand what the best approach is to display all of these commands on the same dashboard?

Do you just add all the nodes to the cluster? Does this negatively affect configuration? Or should you create a cluster per service, per environment? How do meta clusters fit into this?

Thanks in advance, and thanks for all the great work.

Regards
Brian

**Comment by chrisgray** [comment]
Hi @gurrie meta clusters are your answer here! https://github.com/yammer/breakerbox#meta-clusters

Simply add the `metaCluster` with the name of your dashboard that you want to have with all your clusters. This will let it appear in the dashboards dropdown but not let it be configurable. You'll have to still specify the entire cluster in the `config.properties` with all the instances from the different clusters. 

I've considered making a different parser for `config.properties` so that you can simply reference instances or other clusters as a part of that.

**Comment by gurrie** [comment]
Hi,

Thank you for the response. I think it would be incredibly useful to be able to reference other clusters when building up the instances for a meta cluster. 

Regards
Brian

**Comment by chrisgray** [comment]
Agreed! I'll work on getting this in

**Comment by chrisgray** [comment]
Changed the way we configure clusters now in Breakerbox! This new way enables you to reference clusters now!

https://github.com/yammer/breakerbox#dashboard-configuration

**Comment by gurrie** [comment]
Awesome!
