### ISSUE TITLE
Metrics for instances behind a load balancer?

### ISSUE THREAD

**Issue by mlamina** [yammer/breakerbox#20]
I am orchestrating my services using Kubernetes, which means that there are potentially multiple instances of the same service. HTTP requests are distributed evenly between them using a load balancer. 
If I understand it correctly, the breakerbox configuration wants me to define all instances of a cluster manually. However, the amount of instances (and their randomly generated names) are managed by Kubernetes and the load balancer is the only way they may receive HTTP requests.

As a result, if there is more than one instance of a service, the metrics on the dashboard will show incorrect data, because the metrics stream will only be received from one instance behind the load balancer.

I feel like my setup is a very common scenario, so I am wondering if there is a way that I can make breakerbox work with it?

**Comment by chrisgray** [comment]
We have a similar setup that we work with here as well where we have dynamic instances. The problem here is the dynamic discovery is usually pretty custom depending on your exact environment. For example your dynamic environment could be sourced from Kubernetes, Mesos, Zookeeper, Consul, etcd. :-/

Breakerbox uses this https://github.com/yammer/breakerbox/blob/master/breakerbox-service/src/main/java/com/yammer/breakerbox/service/turbine/YamlInstanceDiscovery.java
which simply returns back a Collection<Instances>, so you can provide your own InstanceDiscovery and register it here: https://github.com/yammer/breakerbox/blob/master/breakerbox-service/src/main/java/com/yammer/breakerbox/service/BreakerboxService.java#L112-L113

If your setup is pretty vanilla Kubernetes feel free to implement your KubernetesInstanceDiscovery and submit a PR so others can benefit as well :-)

**Comment by mlamina** [comment]
Thank you for pointing that out! A dynamic instance/cluster discovery would be an amazing feature and I will definitely take a look :)

**Comment by mlamina** [comment]
I created a discovery class for Kubernetes clusters:

https://github.com/yammer/breakerbox/pull/21

However, I am unsure how to properly integrate it so that users can chose which discovery method they'd like to use. Maybe you could take it from here?

**Comment by chrisgray** [comment]
I think we can add something simple to allow for selecting the custom InstanceDiscovery class. I think most likely thing is we can add a dropwizard-configuration parameter 

InstanceDiscovery.impl=com.foo.bar.MyInstanceDiscovery.class where it will default to the YamlInstanceDiscovery, but we can override it to use any custom one (e.g. Kubernetes)

https://github.com/Netflix/Turbine/wiki/Configuration-(1.x)#plugging-in-your-own-instancediscovery-impl

**Comment by chrisgray** [comment]
Just merged in this: https://github.com/yammer/breakerbox/blob/master/breakerbox-service/src/main/java/com/yammer/breakerbox/service/BreakerboxService.java#L235-L244

Which now will allow you to add to the service configuration "instanceDiscoveryClass: com.yammer.breakerbox.turbine.KubernetesInstanceDiscovery" or if that isn't specified it will read from Turbine's "InstanceDiscovery.impl" system property.

It will then add all these instances as well as ones that also come from YamlInstanceDiscovery.

**Comment by mlamina** [comment]
That's awesome! Thank you for the support :) I have one comment regarding the testing of the class that I implemented: It all relies on the Kubernetes client implementation to work properly - I haven't had the time yet to test it in the field, but I will do so tomorrow.

**Comment by chrisgray** [comment]
That would be great! Thank you
